name: Build and deploy to NuGet

on:
  push:
    branches: master
  release:
    types:
      - created
  
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:      
    - uses: actions/checkout@v1
      name: Checkout Code
     
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.0
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore src/skttl.HamApprover.sln
    - name: Build Package for NuGet
      run: msbuild src/skttl.HamApprover.sln /p:Configuration=Release /p:VersionSuffix=build-${{ github.run_number }}
    
#    - name: Push to NuGet
#      run: nuget push src\skttl.HamApprover\bin\Release\*.nupkg ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json -NoSymbols
#      continue-on-error: true
      
    - name: Upload To Github Release
      uses: xresloader/upload-to-github-release@v1.1.2
      with:
        # The files or file patterns to upload. You can upload multiple files by split them by semicolon. You can use the glob pattern to find the files.
        file: src\skttl.HamApprover\bin\Release\*.nupkg;src\skttl.HamApprover\bin\*.zip
        update_latest_release: true
