name: Build and deploy to NuGet

on:
  release:
    types:
      - created
  
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:      
    - uses: actions/checkout@v1
      name: Checkout Code
      
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.0
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore src/skttl.HamApprover.sln
    - name: Build Package for NuGet
      run: msbuild src/skttl.HamApprover.sln /p:Configuration=Release /p:Version="${{ steps.get_version.outputs.VERSION }}"
    
#    - name: Push to NuGet
#      run: nuget push src\skttl.HamApprover\bin\Release\*.nupkg ${{ secrets.NUGET_API_KEY }} -Source https://api.nuget.org/v3/index.json -NoSymbols
#      continue-on-error: true

    - name: Upload assets to a Release
      uses: AButler/upload-release-assets@v2.0
      with:
        # A glob of the files to upload
        files: 'src/skttl.HamApprover/bin/**/*.nupkg;src/skttl.HamApprover/bin/*.zip'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
